### Dumb baseline: predict the mean value for each category

In [3]:
import pandas as pd

In [4]:
train_df = pd.read_csv("../data/student_labels/train.csv")

In [5]:
train_df.head()

,Unnamed: 0,Path,Sex,Age,Frontal/Lateral,AP/PA,No Finding,Enlarged Cardiomediastinum,Cardiomegaly,Lung Opacity,Lung Lesion,Edema,Consolidation,Pneumonia,Atelectasis,Pneumothorax,Pleural Effusion,Pleural Other,Fracture,Support Devices
0,99231,train/pid49995/study1/view2_lateral.jpg,Male,79,Lateral,NaN,-1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,75787,train/pid36892/study6/view1_frontal.jpg,Male,57,Frontal,AP,-1.0,NaN,NaN,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,84568,train/pid12896/study10/view1_frontal.jpg,Male,71,Frontal,PA,-1.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0
3,60377,train/pid14593/study11/view1_frontal.jpg,Male,79,Frontal,AP,-1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
4,218729,train/pid06859/study1/view1_frontal.jpg,Male,35,Frontal,AP,-1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,NaN,NaN,1.0,NaN

In [9]:
diseases = train_df.columns[5:]
disease_to_most_common = {}
for disease in diseases:
    disease_to_most_common[disease] = train_df[disease].mean()
print(disease_to_most_common)

ValueError: No axis named 1 for object type Series

In [7]:
test_df = pd.read_csv("../data/student_labels/test_ids.csv")
test_df.head()

       Id                                    Path
0  180683  test/pid51844/study4/view1_frontal.jpg
1  116607  test/pid55370/study1/view1_frontal.jpg
2  220506  test/pid54607/study1/view1_frontal.jpg
3  180145  test/pid56058/study3/view1_frontal.jpg
4  109578  test/pid56732/study2/view1_frontal.jpg

In [8]:
for k, v in disease_to_most_common.items():
    test_df[k] = v
test_df.head()

       Id                                    Path
0  180683  test/pid51844/study4/view1_frontal.jpg
1  116607  test/pid55370/study1/view1_frontal.jpg
2  220506  test/pid54607/study1/view1_frontal.jpg
3  180145  test/pid56058/study3/view1_frontal.jpg
4  109578  test/pid56732/study2/view1_frontal.jpg

In [31]:
test_df.drop("Path", axis=1, inplace=True)
test_df.to_csv("../results/dumb_baseline.csv", index=False)

(22596, 16)